from typing import TypedDict, List, Annotated, Union 
from operator import add



class AgentState(TypedDict):
    user_input: Annotated[str, "User input from the user to the receptionist agent"]
    agent_call: Annotated[str, "Agent passed the information to another agent by calling them"]
    tool_call: Annotated[str, "Agent can call a tool"]
    user_report: Annotated[dict, "User report where the receptionist asks questions and collects information as a dictionary (question, answer)"]
    user_final_report: Annotated[str, "Final report generated by the user"]
    messages: Annotated[List[dict], "List of messages in the conversation history"]
    agents_conversation_history: Annotated[List[dict], "List of messages in the conversation history between agents"]
    agent_message: Annotated[str, "The message generated by the agent to pass to another agent or to the user"]
    


# agent_messages = AgentState['agent_message']
# agent_messages = "general_agent"

# print(f"AGENT MESSAGE: {agent_messages}")
# agent_messages("surgery_agent")
# print(f"AGENT MESSAGE: {agent_messages}")